export enum Group {
  Admin = "admin",
  Developer = "dev",
  HeadOfBuilding = "bauleitung",
  SeniorBuilder = "architektmeister",
  Builder = "architekt",
  JuniorBuilder = "architektenlehrlin",
  ModeratorLeader = "modleitung",
  Moderator = "mod",
  JrModerator = "moderatorlehrling",
  Designer = "designer",
  SocialMediaManager = "Social-Media-Manager",
  Team = "teammitglied",
  Expert = "Experte",
  YouTuber = "YouTuber",
  Streamer = "Streamer",
  Helper = "Helper",
  Premium = "premium",
  Tester = "tester",
  Guest = "gast",
  Placeholder = "placeholder",
}
