export enum PaintSquadPerk {
  StealthJump = "STEALTH_JUMP",
  InkResistanceUp = "INK_RESISTANCE_UP",
  SquidNinja = "SQUID_NINJA",
  SwimSpeedUp = "SWIM_SPEED_UP",
  RunSpeedUp = "RUN_SPEED_UP",
  SpecialChargeUp = "SPECIAL_CHARGE_UP",
  InkRecoveryUp = "INK_RECOVERY_UP",
  Berserker = "BERSERKER",
  SpecialSaver = "SPECIAL_SAVER",
  Tenacity = "TENACITY",
  Tracker = "TRACKER",
  InkSaverMain = "INK_SAVER_MAIN",
  QuickSuperJump = "QUICK_SUPER_JUMP",
  QuickRespawn = "QUICK_RESPAWN",
  InkSaverSub = "INK_SAVER_SUB",
  JumpArmor = "JUMP_ARMOR",
  InkShield = "INK_SHIELD",
  BombDefenseUp = "BOMB_DEFENSE_UP",
}
