export enum PaintSquadPerkLowercase {
  StealthJump = "stealth_jump",
  InkResistanceUp = "ink_resistance_up",
  SquidNinja = "squid_ninja",
  SwimSpeedUp = "swim_speed_up",
  RunSpeedUp = "run_speed_up",
  SpecialChargeUp = "special_charge_up",
  InkRecoveryUp = "ink_recovery_up",
  Berserker = "berserker",
  SpecialSaver = "special_saver",
  Tenacity = "tenacity",
  Tracker = "tracker",
  InkSaverMain = "ink_saver_main",
  QuickSuperJump = "quick_super_jump",
  QuickRespawn = "quick_respawn",
  InkSaverSub = "ink_saver_sub",
  JumpArmor = "jump_armor",
  InkShield = "ink_shield",
  BombDefenseUp = "bomb_defense_up",
}
